#!/usr/bin/env bash

set -o errexit

function getGlob {
  # linters want to get glob instead of just a list of files
  local IFS=",";

  if [ "$#" -gt 1 ]; then
    echo "{$*}"
  else
    echo "$*"
  fi
}

lessFiles=()
scssFiles=()
cssFiles=()
jsFiles=()
isError=0

for file in "$@"; do
  # skip removed files
  if [ ! -f "$file" ]; then
    continue
  fi

  if [[ "$file" =~ .*$(pwd).*\.js$ ]]; then
    jsFiles+=("$file")
  elif [[ "$file" =~ .*$(pwd).*\.less$ ]]; then
    lessFiles+=("$file")
  elif [[ "$file" =~ .*$(pwd).*\.scss$ ]]; then
    scssFiles+=("$file")
  elif [[ "$file" =~ .*$(pwd).*\.css$ ]]; then
    cssFiles+=("$file")
  fi
done

if [ -n "$lessFiles" ]; then
  stylelint --fix "$(getGlob "${lessFiles[@]}")" --syntax less --cache --config .stylelintrc || isError=$?
fi

if [ -n "$scssFiles" ]; then
  stylelint --fix "$(getGlob "${scssFiles[@]}")" --syntax scss --cache --config .stylelintrc || isError=$?
fi

if [ -n "$cssFiles" ]; then
  stylelint --fix "$(getGlob "${cssFiles[@]}")" --cache --config .stylelintrc || isError=$?
fi

if [ -n "$jsFiles" ]; then
  eslint --fix --cache -c .eslintrc --ext .js "$(getGlob "${jsFiles[@]}")" || isError=$?
fi

exit $isError
